site_name: Mi Portafolio de Redes
site_description: Laboratorios de VM, CML y Packet Tracer
site_author: Gustavo Torres Garnauth

theme:
  language: es
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

extra_css:
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@700&display=swap
  - stylesheets/custom.css

nav:
  - Inicio: index
  - Redes:
    - Lab 3 - Packet Tracer VLANs: labs/lab3-vlans.md
    - Lab 4 - STP en 3 switches: labs/lab-stp-3-switches.md
  - Linux:
    - Lab 1 - DNS en Ubuntu: labs/lab1-dns.md
    - Lab 2 - DHCP en Ubuntu: labs/lab2-dhcp.md
  - Docker:
    - Introducción: docker/index.md
  - Automatizacion:
    - Lab 1:

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
